# Generated by Django 4.0.4 on 2022-09-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paquetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_envio', models.CharField(max_length=100, verbose_name='Direccion envio')),
                ('nombre_remitente', models.CharField(max_length=100, verbose_name='remitente')),
                ('nombre_destinatario', models.CharField(max_length=100, verbose_name='remitente')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='fecha de creación')),
                ('estado', models.BooleanField(default=True, verbose_name='en transito/ entregado')),
                ('peso', models.IntegerField(max_length=10, verbose_name='peso en kg')),
                ('tamano', models.CharField(max_length=50, verbose_name='mensajeria/basico/sobredimensionado')),
                ('fecha_entrega', models.DateField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
        ),
    ]
