# Generated by Django 4.0.4 on 2022-09-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPaquetes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquetes',
            name='nombre_destinatario',
            field=models.CharField(max_length=100, verbose_name='destinatario'),
        ),
        migrations.AlterField(
            model_name='paquetes',
            name='tamano',
            field=models.CharField(choices=[('M', 'Mensajereia'), ('B', 'Basico'), ('S', 'Sobre Dimensionado')], default='M', max_length=1, verbose_name='mensajeria/basico/sobredimensionado'),
        ),
    ]
