# Generated by Django 4.0.4 on 2022-10-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPaquetes', '0002_alter_paquetes_nombre_destinatario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquetes',
            name='peso',
            field=models.IntegerField(verbose_name='peso en kg'),
        ),
    ]
